// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	gateway "github.com/ro-eng/mcp-proxy/gateway"
	mock "github.com/stretchr/testify/mock"
)

// MockAuditLogger is an autogenerated mock type for the AuditLogger type
type MockAuditLogger struct {
	mock.Mock
}

type MockAuditLogger_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuditLogger) EXPECT() *MockAuditLogger_Expecter {
	return &MockAuditLogger_Expecter{mock: &_m.Mock}
}

// Emit provides a mock function with given fields: ctx, event
func (_m *MockAuditLogger) Emit(ctx context.Context, event *gateway.AuditEvent) error {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for Emit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gateway.AuditEvent) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuditLogger_Emit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Emit'
type MockAuditLogger_Emit_Call struct {
	*mock.Call
}

// Emit is a helper method to define mock.On call
//   - ctx context.Context
//   - event *gateway.AuditEvent
func (_e *MockAuditLogger_Expecter) Emit(ctx interface{}, event interface{}) *MockAuditLogger_Emit_Call {
	return &MockAuditLogger_Emit_Call{Call: _e.mock.On("Emit", ctx, event)}
}

func (_c *MockAuditLogger_Emit_Call) Run(run func(ctx context.Context, event *gateway.AuditEvent)) *MockAuditLogger_Emit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*gateway.AuditEvent))
	})
	return _c
}

func (_c *MockAuditLogger_Emit_Call) Return(_a0 error) *MockAuditLogger_Emit_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuditLogger_Emit_Call) RunAndReturn(run func(context.Context, *gateway.AuditEvent) error) *MockAuditLogger_Emit_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyChain provides a mock function with given fields: ctx, instanceID
func (_m *MockAuditLogger) VerifyChain(ctx context.Context, instanceID string) error {
	ret := _m.Called(ctx, instanceID)

	if len(ret) == 0 {
		panic("no return value specified for VerifyChain")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, instanceID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuditLogger_VerifyChain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyChain'
type MockAuditLogger_VerifyChain_Call struct {
	*mock.Call
}

// VerifyChain is a helper method to define mock.On call
//   - ctx context.Context
//   - instanceID string
func (_e *MockAuditLogger_Expecter) VerifyChain(ctx interface{}, instanceID interface{}) *MockAuditLogger_VerifyChain_Call {
	return &MockAuditLogger_VerifyChain_Call{Call: _e.mock.On("VerifyChain", ctx, instanceID)}
}

func (_c *MockAuditLogger_VerifyChain_Call) Run(run func(ctx context.Context, instanceID string)) *MockAuditLogger_VerifyChain_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAuditLogger_VerifyChain_Call) Return(_a0 error) *MockAuditLogger_VerifyChain_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuditLogger_VerifyChain_Call) RunAndReturn(run func(context.Context, string) error) *MockAuditLogger_VerifyChain_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuditLogger creates a new instance of MockAuditLogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuditLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuditLogger {
	mock := &MockAuditLogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
