// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	gateway "github.com/ro-eng/mcp-proxy/gateway"
	mock "github.com/stretchr/testify/mock"
)

// MockCredentialResolver is an autogenerated mock type for the CredentialResolver type
type MockCredentialResolver struct {
	mock.Mock
}

type MockCredentialResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCredentialResolver) EXPECT() *MockCredentialResolver_Expecter {
	return &MockCredentialResolver_Expecter{mock: &_m.Mock}
}

// Resolve provides a mock function with given fields: ctx, identity, server
func (_m *MockCredentialResolver) Resolve(ctx context.Context, identity *gateway.Identity, server *gateway.ServerConfig) (*gateway.Credential, error) {
	ret := _m.Called(ctx, identity, server)

	if len(ret) == 0 {
		panic("no return value specified for Resolve")
	}

	var r0 *gateway.Credential
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gateway.Identity, *gateway.ServerConfig) (*gateway.Credential, error)); ok {
		return rf(ctx, identity, server)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gateway.Identity, *gateway.ServerConfig) *gateway.Credential); ok {
		r0 = rf(ctx, identity, server)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gateway.Credential)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gateway.Identity, *gateway.ServerConfig) error); ok {
		r1 = rf(ctx, identity, server)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCredentialResolver_Resolve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resolve'
type MockCredentialResolver_Resolve_Call struct {
	*mock.Call
}

// Resolve is a helper method to define mock.On call
//   - ctx context.Context
//   - identity *gateway.Identity
//   - server *gateway.ServerConfig
func (_e *MockCredentialResolver_Expecter) Resolve(ctx interface{}, identity interface{}, server interface{}) *MockCredentialResolver_Resolve_Call {
	return &MockCredentialResolver_Resolve_Call{Call: _e.mock.On("Resolve", ctx, identity, server)}
}

func (_c *MockCredentialResolver_Resolve_Call) Run(run func(ctx context.Context, identity *gateway.Identity, server *gateway.ServerConfig)) *MockCredentialResolver_Resolve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*gateway.Identity), args[2].(*gateway.ServerConfig))
	})
	return _c
}

func (_c *MockCredentialResolver_Resolve_Call) Return(_a0 *gateway.Credential, _a1 error) *MockCredentialResolver_Resolve_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCredentialResolver_Resolve_Call) RunAndReturn(run func(context.Context, *gateway.Identity, *gateway.ServerConfig) (*gateway.Credential, error)) *MockCredentialResolver_Resolve_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCredentialResolver creates a new instance of MockCredentialResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCredentialResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCredentialResolver {
	mock := &MockCredentialResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
