// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	gateway "github.com/jphines/mcp-proxy/gateway"
	mock "github.com/stretchr/testify/mock"
)

// MockTokenExchanger is an autogenerated mock type for the TokenExchanger type
type MockTokenExchanger struct {
	mock.Mock
}

type MockTokenExchanger_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenExchanger) EXPECT() *MockTokenExchanger_Expecter {
	return &MockTokenExchanger_Expecter{mock: &_m.Mock}
}

// Exchange provides a mock function with given fields: ctx, identity, serviceID
func (_m *MockTokenExchanger) Exchange(ctx context.Context, identity *gateway.Identity, serviceID string) (*gateway.Credential, error) {
	ret := _m.Called(ctx, identity, serviceID)

	if len(ret) == 0 {
		panic("no return value specified for Exchange")
	}

	var r0 *gateway.Credential
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gateway.Identity, string) (*gateway.Credential, error)); ok {
		return rf(ctx, identity, serviceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gateway.Identity, string) *gateway.Credential); ok {
		r0 = rf(ctx, identity, serviceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gateway.Credential)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gateway.Identity, string) error); ok {
		r1 = rf(ctx, identity, serviceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTokenExchanger_Exchange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exchange'
type MockTokenExchanger_Exchange_Call struct {
	*mock.Call
}

// Exchange is a helper method to define mock.On call
//   - ctx context.Context
//   - identity *gateway.Identity
//   - serviceID string
func (_e *MockTokenExchanger_Expecter) Exchange(ctx interface{}, identity interface{}, serviceID interface{}) *MockTokenExchanger_Exchange_Call {
	return &MockTokenExchanger_Exchange_Call{Call: _e.mock.On("Exchange", ctx, identity, serviceID)}
}

func (_c *MockTokenExchanger_Exchange_Call) Run(run func(ctx context.Context, identity *gateway.Identity, serviceID string)) *MockTokenExchanger_Exchange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*gateway.Identity), args[2].(string))
	})
	return _c
}

func (_c *MockTokenExchanger_Exchange_Call) Return(_a0 *gateway.Credential, _a1 error) *MockTokenExchanger_Exchange_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTokenExchanger_Exchange_Call) RunAndReturn(run func(context.Context, *gateway.Identity, string) (*gateway.Credential, error)) *MockTokenExchanger_Exchange_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenExchanger creates a new instance of MockTokenExchanger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenExchanger(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenExchanger {
	mock := &MockTokenExchanger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
