// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	gateway "github.com/ro-eng/mcp-proxy/gateway"
	mock "github.com/stretchr/testify/mock"
)

// MockOAuthEnrollment is an autogenerated mock type for the OAuthEnrollment type
type MockOAuthEnrollment struct {
	mock.Mock
}

type MockOAuthEnrollment_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOAuthEnrollment) EXPECT() *MockOAuthEnrollment_Expecter {
	return &MockOAuthEnrollment_Expecter{mock: &_m.Mock}
}

// HandleCallback provides a mock function with given fields: ctx, code, stateParam
func (_m *MockOAuthEnrollment) HandleCallback(ctx context.Context, code string, stateParam string) error {
	ret := _m.Called(ctx, code, stateParam)

	if len(ret) == 0 {
		panic("no return value specified for HandleCallback")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, code, stateParam)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOAuthEnrollment_HandleCallback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleCallback'
type MockOAuthEnrollment_HandleCallback_Call struct {
	*mock.Call
}

// HandleCallback is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
//   - stateParam string
func (_e *MockOAuthEnrollment_Expecter) HandleCallback(ctx interface{}, code interface{}, stateParam interface{}) *MockOAuthEnrollment_HandleCallback_Call {
	return &MockOAuthEnrollment_HandleCallback_Call{Call: _e.mock.On("HandleCallback", ctx, code, stateParam)}
}

func (_c *MockOAuthEnrollment_HandleCallback_Call) Run(run func(ctx context.Context, code string, stateParam string)) *MockOAuthEnrollment_HandleCallback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockOAuthEnrollment_HandleCallback_Call) Return(_a0 error) *MockOAuthEnrollment_HandleCallback_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOAuthEnrollment_HandleCallback_Call) RunAndReturn(run func(context.Context, string, string) error) *MockOAuthEnrollment_HandleCallback_Call {
	_c.Call.Return(run)
	return _c
}

// InitiateFlow provides a mock function with given fields: ctx, identity, serviceID
func (_m *MockOAuthEnrollment) InitiateFlow(ctx context.Context, identity *gateway.Identity, serviceID string) (string, error) {
	ret := _m.Called(ctx, identity, serviceID)

	if len(ret) == 0 {
		panic("no return value specified for InitiateFlow")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gateway.Identity, string) (string, error)); ok {
		return rf(ctx, identity, serviceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gateway.Identity, string) string); ok {
		r0 = rf(ctx, identity, serviceID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gateway.Identity, string) error); ok {
		r1 = rf(ctx, identity, serviceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOAuthEnrollment_InitiateFlow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InitiateFlow'
type MockOAuthEnrollment_InitiateFlow_Call struct {
	*mock.Call
}

// InitiateFlow is a helper method to define mock.On call
//   - ctx context.Context
//   - identity *gateway.Identity
//   - serviceID string
func (_e *MockOAuthEnrollment_Expecter) InitiateFlow(ctx interface{}, identity interface{}, serviceID interface{}) *MockOAuthEnrollment_InitiateFlow_Call {
	return &MockOAuthEnrollment_InitiateFlow_Call{Call: _e.mock.On("InitiateFlow", ctx, identity, serviceID)}
}

func (_c *MockOAuthEnrollment_InitiateFlow_Call) Run(run func(ctx context.Context, identity *gateway.Identity, serviceID string)) *MockOAuthEnrollment_InitiateFlow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*gateway.Identity), args[2].(string))
	})
	return _c
}

func (_c *MockOAuthEnrollment_InitiateFlow_Call) Return(authURL string, err error) *MockOAuthEnrollment_InitiateFlow_Call {
	_c.Call.Return(authURL, err)
	return _c
}

func (_c *MockOAuthEnrollment_InitiateFlow_Call) RunAndReturn(run func(context.Context, *gateway.Identity, string) (string, error)) *MockOAuthEnrollment_InitiateFlow_Call {
	_c.Call.Return(run)
	return _c
}

// IsEnrolled provides a mock function with given fields: ctx, identity, serviceID
func (_m *MockOAuthEnrollment) IsEnrolled(ctx context.Context, identity *gateway.Identity, serviceID string) (bool, error) {
	ret := _m.Called(ctx, identity, serviceID)

	if len(ret) == 0 {
		panic("no return value specified for IsEnrolled")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gateway.Identity, string) (bool, error)); ok {
		return rf(ctx, identity, serviceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gateway.Identity, string) bool); ok {
		r0 = rf(ctx, identity, serviceID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gateway.Identity, string) error); ok {
		r1 = rf(ctx, identity, serviceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOAuthEnrollment_IsEnrolled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsEnrolled'
type MockOAuthEnrollment_IsEnrolled_Call struct {
	*mock.Call
}

// IsEnrolled is a helper method to define mock.On call
//   - ctx context.Context
//   - identity *gateway.Identity
//   - serviceID string
func (_e *MockOAuthEnrollment_Expecter) IsEnrolled(ctx interface{}, identity interface{}, serviceID interface{}) *MockOAuthEnrollment_IsEnrolled_Call {
	return &MockOAuthEnrollment_IsEnrolled_Call{Call: _e.mock.On("IsEnrolled", ctx, identity, serviceID)}
}

func (_c *MockOAuthEnrollment_IsEnrolled_Call) Run(run func(ctx context.Context, identity *gateway.Identity, serviceID string)) *MockOAuthEnrollment_IsEnrolled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*gateway.Identity), args[2].(string))
	})
	return _c
}

func (_c *MockOAuthEnrollment_IsEnrolled_Call) Return(_a0 bool, _a1 error) *MockOAuthEnrollment_IsEnrolled_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOAuthEnrollment_IsEnrolled_Call) RunAndReturn(run func(context.Context, *gateway.Identity, string) (bool, error)) *MockOAuthEnrollment_IsEnrolled_Call {
	_c.Call.Return(run)
	return _c
}

// Revoke provides a mock function with given fields: ctx, identity, serviceID
func (_m *MockOAuthEnrollment) Revoke(ctx context.Context, identity *gateway.Identity, serviceID string) error {
	ret := _m.Called(ctx, identity, serviceID)

	if len(ret) == 0 {
		panic("no return value specified for Revoke")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gateway.Identity, string) error); ok {
		r0 = rf(ctx, identity, serviceID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOAuthEnrollment_Revoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Revoke'
type MockOAuthEnrollment_Revoke_Call struct {
	*mock.Call
}

// Revoke is a helper method to define mock.On call
//   - ctx context.Context
//   - identity *gateway.Identity
//   - serviceID string
func (_e *MockOAuthEnrollment_Expecter) Revoke(ctx interface{}, identity interface{}, serviceID interface{}) *MockOAuthEnrollment_Revoke_Call {
	return &MockOAuthEnrollment_Revoke_Call{Call: _e.mock.On("Revoke", ctx, identity, serviceID)}
}

func (_c *MockOAuthEnrollment_Revoke_Call) Run(run func(ctx context.Context, identity *gateway.Identity, serviceID string)) *MockOAuthEnrollment_Revoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*gateway.Identity), args[2].(string))
	})
	return _c
}

func (_c *MockOAuthEnrollment_Revoke_Call) Return(_a0 error) *MockOAuthEnrollment_Revoke_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOAuthEnrollment_Revoke_Call) RunAndReturn(run func(context.Context, *gateway.Identity, string) error) *MockOAuthEnrollment_Revoke_Call {
	_c.Call.Return(run)
	return _c
}

// AccessToken provides a mock function with given fields: ctx, identity, serviceID
func (_m *MockOAuthEnrollment) AccessToken(ctx context.Context, identity *gateway.Identity, serviceID string) (*gateway.Credential, error) {
	ret := _m.Called(ctx, identity, serviceID)

	if len(ret) == 0 {
		panic("no return value specified for AccessToken")
	}

	var r0 *gateway.Credential
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gateway.Identity, string) (*gateway.Credential, error)); ok {
		return rf(ctx, identity, serviceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gateway.Identity, string) *gateway.Credential); ok {
		r0 = rf(ctx, identity, serviceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gateway.Credential)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gateway.Identity, string) error); ok {
		r1 = rf(ctx, identity, serviceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOAuthEnrollment_AccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AccessToken'
type MockOAuthEnrollment_AccessToken_Call struct {
	*mock.Call
}

func (_e *MockOAuthEnrollment_Expecter) AccessToken(ctx interface{}, identity interface{}, serviceID interface{}) *MockOAuthEnrollment_AccessToken_Call {
	return &MockOAuthEnrollment_AccessToken_Call{Call: _e.mock.On("AccessToken", ctx, identity, serviceID)}
}

func (_c *MockOAuthEnrollment_AccessToken_Call) Run(run func(ctx context.Context, identity *gateway.Identity, serviceID string)) *MockOAuthEnrollment_AccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*gateway.Identity), args[2].(string))
	})
	return _c
}

func (_c *MockOAuthEnrollment_AccessToken_Call) Return(_a0 *gateway.Credential, _a1 error) *MockOAuthEnrollment_AccessToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOAuthEnrollment_AccessToken_Call) RunAndReturn(run func(context.Context, *gateway.Identity, string) (*gateway.Credential, error)) *MockOAuthEnrollment_AccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOAuthEnrollment creates a new instance of MockOAuthEnrollment. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOAuthEnrollment(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOAuthEnrollment {
	mock := &MockOAuthEnrollment{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
