// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	gateway "github.com/ro-eng/mcp-proxy/gateway"
	mock "github.com/stretchr/testify/mock"
)

// MockApprovalService is an autogenerated mock type for the ApprovalService type
type MockApprovalService struct {
	mock.Mock
}

type MockApprovalService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockApprovalService) EXPECT() *MockApprovalService_Expecter {
	return &MockApprovalService_Expecter{mock: &_m.Mock}
}

// Decide provides a mock function with given fields: ctx, decision
func (_m *MockApprovalService) Decide(ctx context.Context, decision *gateway.ApprovalDecision) error {
	ret := _m.Called(ctx, decision)

	if len(ret) == 0 {
		panic("no return value specified for Decide")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gateway.ApprovalDecision) error); ok {
		r0 = rf(ctx, decision)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockApprovalService_Decide_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decide'
type MockApprovalService_Decide_Call struct {
	*mock.Call
}

// Decide is a helper method to define mock.On call
//   - ctx context.Context
//   - decision *gateway.ApprovalDecision
func (_e *MockApprovalService_Expecter) Decide(ctx interface{}, decision interface{}) *MockApprovalService_Decide_Call {
	return &MockApprovalService_Decide_Call{Call: _e.mock.On("Decide", ctx, decision)}
}

func (_c *MockApprovalService_Decide_Call) Run(run func(ctx context.Context, decision *gateway.ApprovalDecision)) *MockApprovalService_Decide_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*gateway.ApprovalDecision))
	})
	return _c
}

func (_c *MockApprovalService_Decide_Call) Return(_a0 error) *MockApprovalService_Decide_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockApprovalService_Decide_Call) RunAndReturn(run func(context.Context, *gateway.ApprovalDecision) error) *MockApprovalService_Decide_Call {
	_c.Call.Return(run)
	return _c
}

// Request provides a mock function with given fields: ctx, req
func (_m *MockApprovalService) Request(ctx context.Context, req *gateway.ApprovalRequest) (*gateway.ApprovalDecision, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Request")
	}

	var r0 *gateway.ApprovalDecision
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gateway.ApprovalRequest) (*gateway.ApprovalDecision, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gateway.ApprovalRequest) *gateway.ApprovalDecision); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gateway.ApprovalDecision)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gateway.ApprovalRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockApprovalService_Request_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Request'
type MockApprovalService_Request_Call struct {
	*mock.Call
}

// Request is a helper method to define mock.On call
//   - ctx context.Context
//   - req *gateway.ApprovalRequest
func (_e *MockApprovalService_Expecter) Request(ctx interface{}, req interface{}) *MockApprovalService_Request_Call {
	return &MockApprovalService_Request_Call{Call: _e.mock.On("Request", ctx, req)}
}

func (_c *MockApprovalService_Request_Call) Run(run func(ctx context.Context, req *gateway.ApprovalRequest)) *MockApprovalService_Request_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*gateway.ApprovalRequest))
	})
	return _c
}

func (_c *MockApprovalService_Request_Call) Return(_a0 *gateway.ApprovalDecision, _a1 error) *MockApprovalService_Request_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockApprovalService_Request_Call) RunAndReturn(run func(context.Context, *gateway.ApprovalRequest) (*gateway.ApprovalDecision, error)) *MockApprovalService_Request_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockApprovalService creates a new instance of MockApprovalService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockApprovalService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockApprovalService {
	mock := &MockApprovalService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
