// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	gateway "github.com/ro-eng/mcp-proxy/gateway"
	mock "github.com/stretchr/testify/mock"
)

// MockServerRegistry is an autogenerated mock type for the ServerRegistry type
type MockServerRegistry struct {
	mock.Mock
}

type MockServerRegistry_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServerRegistry) EXPECT() *MockServerRegistry_Expecter {
	return &MockServerRegistry_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockServerRegistry) Get(ctx context.Context, id string) (*gateway.ServerConfig, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *gateway.ServerConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*gateway.ServerConfig, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *gateway.ServerConfig); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gateway.ServerConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServerRegistry_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockServerRegistry_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockServerRegistry_Expecter) Get(ctx interface{}, id interface{}) *MockServerRegistry_Get_Call {
	return &MockServerRegistry_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockServerRegistry_Get_Call) Run(run func(ctx context.Context, id string)) *MockServerRegistry_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockServerRegistry_Get_Call) Return(_a0 *gateway.ServerConfig, _a1 error) *MockServerRegistry_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServerRegistry_Get_Call) RunAndReturn(run func(context.Context, string) (*gateway.ServerConfig, error)) *MockServerRegistry_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, filter
func (_m *MockServerRegistry) List(ctx context.Context, filter *gateway.ServerFilter) ([]*gateway.ServerConfig, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*gateway.ServerConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gateway.ServerFilter) ([]*gateway.ServerConfig, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gateway.ServerFilter) []*gateway.ServerConfig); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*gateway.ServerConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gateway.ServerFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServerRegistry_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockServerRegistry_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter *gateway.ServerFilter
func (_e *MockServerRegistry_Expecter) List(ctx interface{}, filter interface{}) *MockServerRegistry_List_Call {
	return &MockServerRegistry_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *MockServerRegistry_List_Call) Run(run func(ctx context.Context, filter *gateway.ServerFilter)) *MockServerRegistry_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*gateway.ServerFilter))
	})
	return _c
}

func (_c *MockServerRegistry_List_Call) Return(_a0 []*gateway.ServerConfig, _a1 error) *MockServerRegistry_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServerRegistry_List_Call) RunAndReturn(run func(context.Context, *gateway.ServerFilter) ([]*gateway.ServerConfig, error)) *MockServerRegistry_List_Call {
	_c.Call.Return(run)
	return _c
}

// ToolCatalog provides a mock function with given fields: ctx, identity
func (_m *MockServerRegistry) ToolCatalog(ctx context.Context, identity *gateway.Identity) ([]gateway.Tool, error) {
	ret := _m.Called(ctx, identity)

	if len(ret) == 0 {
		panic("no return value specified for ToolCatalog")
	}

	var r0 []gateway.Tool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gateway.Identity) ([]gateway.Tool, error)); ok {
		return rf(ctx, identity)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gateway.Identity) []gateway.Tool); ok {
		r0 = rf(ctx, identity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]gateway.Tool)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gateway.Identity) error); ok {
		r1 = rf(ctx, identity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServerRegistry_ToolCatalog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToolCatalog'
type MockServerRegistry_ToolCatalog_Call struct {
	*mock.Call
}

// ToolCatalog is a helper method to define mock.On call
//   - ctx context.Context
//   - identity *gateway.Identity
func (_e *MockServerRegistry_Expecter) ToolCatalog(ctx interface{}, identity interface{}) *MockServerRegistry_ToolCatalog_Call {
	return &MockServerRegistry_ToolCatalog_Call{Call: _e.mock.On("ToolCatalog", ctx, identity)}
}

func (_c *MockServerRegistry_ToolCatalog_Call) Run(run func(ctx context.Context, identity *gateway.Identity)) *MockServerRegistry_ToolCatalog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*gateway.Identity))
	})
	return _c
}

func (_c *MockServerRegistry_ToolCatalog_Call) Return(_a0 []gateway.Tool, _a1 error) *MockServerRegistry_ToolCatalog_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServerRegistry_ToolCatalog_Call) RunAndReturn(run func(context.Context, *gateway.Identity) ([]gateway.Tool, error)) *MockServerRegistry_ToolCatalog_Call {
	_c.Call.Return(run)
	return _c
}

// Execute provides a mock function with given fields: ctx, serverID, fn
func (_m *MockServerRegistry) Execute(ctx context.Context, serverID string, fn func() error) error {
	ret := _m.Called(ctx, serverID, fn)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	if rf, ok := ret.Get(0).(func(context.Context, string, func() error) error); ok {
		return rf(ctx, serverID, fn)
	}
	return ret.Error(0)
}

// MockServerRegistry_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockServerRegistry_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID string
//   - fn func() error
func (_e *MockServerRegistry_Expecter) Execute(ctx interface{}, serverID interface{}, fn interface{}) *MockServerRegistry_Execute_Call {
	return &MockServerRegistry_Execute_Call{Call: _e.mock.On("Execute", ctx, serverID, fn)}
}

func (_c *MockServerRegistry_Execute_Call) Run(run func(ctx context.Context, serverID string, fn func() error)) *MockServerRegistry_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(func() error))
	})
	return _c
}

func (_c *MockServerRegistry_Execute_Call) Return(_a0 error) *MockServerRegistry_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServerRegistry_Execute_Call) RunAndReturn(run func(context.Context, string, func() error) error) *MockServerRegistry_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockServerRegistry creates a new instance of MockServerRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServerRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServerRegistry {
	mock := &MockServerRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
