// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	gateway "github.com/jphines/mcp-proxy/gateway"
	mock "github.com/stretchr/testify/mock"
)

// MockPolicyEngine is an autogenerated mock type for the PolicyEngine type
type MockPolicyEngine struct {
	mock.Mock
}

type MockPolicyEngine_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPolicyEngine) EXPECT() *MockPolicyEngine_Expecter {
	return &MockPolicyEngine_Expecter{mock: &_m.Mock}
}

// Evaluate provides a mock function with given fields: ctx, identity, call
func (_m *MockPolicyEngine) Evaluate(ctx context.Context, identity *gateway.Identity, call *gateway.ToolCall) (*gateway.PolicyDecision, error) {
	ret := _m.Called(ctx, identity, call)

	if len(ret) == 0 {
		panic("no return value specified for Evaluate")
	}

	var r0 *gateway.PolicyDecision
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gateway.Identity, *gateway.ToolCall) (*gateway.PolicyDecision, error)); ok {
		return rf(ctx, identity, call)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gateway.Identity, *gateway.ToolCall) *gateway.PolicyDecision); ok {
		r0 = rf(ctx, identity, call)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gateway.PolicyDecision)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gateway.Identity, *gateway.ToolCall) error); ok {
		r1 = rf(ctx, identity, call)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPolicyEngine_Evaluate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Evaluate'
type MockPolicyEngine_Evaluate_Call struct {
	*mock.Call
}

// Evaluate is a helper method to define mock.On call
//   - ctx context.Context
//   - identity *gateway.Identity
//   - call *gateway.ToolCall
func (_e *MockPolicyEngine_Expecter) Evaluate(ctx interface{}, identity interface{}, call interface{}) *MockPolicyEngine_Evaluate_Call {
	return &MockPolicyEngine_Evaluate_Call{Call: _e.mock.On("Evaluate", ctx, identity, call)}
}

func (_c *MockPolicyEngine_Evaluate_Call) Run(run func(ctx context.Context, identity *gateway.Identity, call *gateway.ToolCall)) *MockPolicyEngine_Evaluate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*gateway.Identity), args[2].(*gateway.ToolCall))
	})
	return _c
}

func (_c *MockPolicyEngine_Evaluate_Call) Return(_a0 *gateway.PolicyDecision, _a1 error) *MockPolicyEngine_Evaluate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPolicyEngine_Evaluate_Call) RunAndReturn(run func(context.Context, *gateway.Identity, *gateway.ToolCall) (*gateway.PolicyDecision, error)) *MockPolicyEngine_Evaluate_Call {
	_c.Call.Return(run)
	return _c
}

// Reload provides a mock function with given fields: ctx
func (_m *MockPolicyEngine) Reload(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Reload")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPolicyEngine_Reload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reload'
type MockPolicyEngine_Reload_Call struct {
	*mock.Call
}

// Reload is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPolicyEngine_Expecter) Reload(ctx interface{}) *MockPolicyEngine_Reload_Call {
	return &MockPolicyEngine_Reload_Call{Call: _e.mock.On("Reload", ctx)}
}

func (_c *MockPolicyEngine_Reload_Call) Run(run func(ctx context.Context)) *MockPolicyEngine_Reload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockPolicyEngine_Reload_Call) Return(_a0 error) *MockPolicyEngine_Reload_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPolicyEngine_Reload_Call) RunAndReturn(run func(context.Context) error) *MockPolicyEngine_Reload_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPolicyEngine creates a new instance of MockPolicyEngine. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPolicyEngine(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPolicyEngine {
	mock := &MockPolicyEngine{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
