// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockMetricsCollector is an autogenerated mock type for the MetricsCollector type
type MockMetricsCollector struct {
	mock.Mock
}

type MockMetricsCollector_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMetricsCollector) EXPECT() *MockMetricsCollector_Expecter {
	return &MockMetricsCollector_Expecter{mock: &_m.Mock}
}

// ActiveSessions provides a mock function with given fields: delta
func (_m *MockMetricsCollector) ActiveSessions(delta int) {
	_m.Called(delta)
}

// MockMetricsCollector_ActiveSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ActiveSessions'
type MockMetricsCollector_ActiveSessions_Call struct {
	*mock.Call
}

// ActiveSessions is a helper method to define mock.On call
//   - delta int
func (_e *MockMetricsCollector_Expecter) ActiveSessions(delta interface{}) *MockMetricsCollector_ActiveSessions_Call {
	return &MockMetricsCollector_ActiveSessions_Call{Call: _e.mock.On("ActiveSessions", delta)}
}

func (_c *MockMetricsCollector_ActiveSessions_Call) Run(run func(delta int)) *MockMetricsCollector_ActiveSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockMetricsCollector_ActiveSessions_Call) Return() *MockMetricsCollector_ActiveSessions_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockMetricsCollector_ActiveSessions_Call) RunAndReturn(run func(int)) *MockMetricsCollector_ActiveSessions_Call {
	_c.Run(run)
	return _c
}

// ApprovalWaitDuration provides a mock function with given fields: serverID, ms
func (_m *MockMetricsCollector) ApprovalWaitDuration(serverID string, ms int64) {
	_m.Called(serverID, ms)
}

// MockMetricsCollector_ApprovalWaitDuration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApprovalWaitDuration'
type MockMetricsCollector_ApprovalWaitDuration_Call struct {
	*mock.Call
}

// ApprovalWaitDuration is a helper method to define mock.On call
//   - serverID string
//   - ms int64
func (_e *MockMetricsCollector_Expecter) ApprovalWaitDuration(serverID interface{}, ms interface{}) *MockMetricsCollector_ApprovalWaitDuration_Call {
	return &MockMetricsCollector_ApprovalWaitDuration_Call{Call: _e.mock.On("ApprovalWaitDuration", serverID, ms)}
}

func (_c *MockMetricsCollector_ApprovalWaitDuration_Call) Run(run func(serverID string, ms int64)) *MockMetricsCollector_ApprovalWaitDuration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(int64))
	})
	return _c
}

func (_c *MockMetricsCollector_ApprovalWaitDuration_Call) Return() *MockMetricsCollector_ApprovalWaitDuration_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockMetricsCollector_ApprovalWaitDuration_Call) RunAndReturn(run func(string, int64)) *MockMetricsCollector_ApprovalWaitDuration_Call {
	_c.Run(run)
	return _c
}

// CircuitBreakerState provides a mock function with given fields: serverID, state
func (_m *MockMetricsCollector) CircuitBreakerState(serverID string, state int) {
	_m.Called(serverID, state)
}

// MockMetricsCollector_CircuitBreakerState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CircuitBreakerState'
type MockMetricsCollector_CircuitBreakerState_Call struct {
	*mock.Call
}

// CircuitBreakerState is a helper method to define mock.On call
//   - serverID string
//   - state int
func (_e *MockMetricsCollector_Expecter) CircuitBreakerState(serverID interface{}, state interface{}) *MockMetricsCollector_CircuitBreakerState_Call {
	return &MockMetricsCollector_CircuitBreakerState_Call{Call: _e.mock.On("CircuitBreakerState", serverID, state)}
}

func (_c *MockMetricsCollector_CircuitBreakerState_Call) Run(run func(serverID string, state int)) *MockMetricsCollector_CircuitBreakerState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(int))
	})
	return _c
}

func (_c *MockMetricsCollector_CircuitBreakerState_Call) Return() *MockMetricsCollector_CircuitBreakerState_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockMetricsCollector_CircuitBreakerState_Call) RunAndReturn(run func(string, int)) *MockMetricsCollector_CircuitBreakerState_Call {
	_c.Run(run)
	return _c
}

// CredentialResolutionDuration provides a mock function with given fields: serverID, strategy, ms
func (_m *MockMetricsCollector) CredentialResolutionDuration(serverID string, strategy string, ms int64) {
	_m.Called(serverID, strategy, ms)
}

// MockMetricsCollector_CredentialResolutionDuration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CredentialResolutionDuration'
type MockMetricsCollector_CredentialResolutionDuration_Call struct {
	*mock.Call
}

// CredentialResolutionDuration is a helper method to define mock.On call
//   - serverID string
//   - strategy string
//   - ms int64
func (_e *MockMetricsCollector_Expecter) CredentialResolutionDuration(serverID interface{}, strategy interface{}, ms interface{}) *MockMetricsCollector_CredentialResolutionDuration_Call {
	return &MockMetricsCollector_CredentialResolutionDuration_Call{Call: _e.mock.On("CredentialResolutionDuration", serverID, strategy, ms)}
}

func (_c *MockMetricsCollector_CredentialResolutionDuration_Call) Run(run func(serverID string, strategy string, ms int64)) *MockMetricsCollector_CredentialResolutionDuration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(int64))
	})
	return _c
}

func (_c *MockMetricsCollector_CredentialResolutionDuration_Call) Return() *MockMetricsCollector_CredentialResolutionDuration_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockMetricsCollector_CredentialResolutionDuration_Call) RunAndReturn(run func(string, string, int64)) *MockMetricsCollector_CredentialResolutionDuration_Call {
	_c.Run(run)
	return _c
}

// DownstreamDuration provides a mock function with given fields: serverID, ms
func (_m *MockMetricsCollector) DownstreamDuration(serverID string, ms int64) {
	_m.Called(serverID, ms)
}

// MockMetricsCollector_DownstreamDuration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DownstreamDuration'
type MockMetricsCollector_DownstreamDuration_Call struct {
	*mock.Call
}

// DownstreamDuration is a helper method to define mock.On call
//   - serverID string
//   - ms int64
func (_e *MockMetricsCollector_Expecter) DownstreamDuration(serverID interface{}, ms interface{}) *MockMetricsCollector_DownstreamDuration_Call {
	return &MockMetricsCollector_DownstreamDuration_Call{Call: _e.mock.On("DownstreamDuration", serverID, ms)}
}

func (_c *MockMetricsCollector_DownstreamDuration_Call) Run(run func(serverID string, ms int64)) *MockMetricsCollector_DownstreamDuration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(int64))
	})
	return _c
}

func (_c *MockMetricsCollector_DownstreamDuration_Call) Return() *MockMetricsCollector_DownstreamDuration_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockMetricsCollector_DownstreamDuration_Call) RunAndReturn(run func(string, int64)) *MockMetricsCollector_DownstreamDuration_Call {
	_c.Run(run)
	return _c
}

// DownstreamError provides a mock function with given fields: serverID, toolName, errType
func (_m *MockMetricsCollector) DownstreamError(serverID string, toolName string, errType string) {
	_m.Called(serverID, toolName, errType)
}

// MockMetricsCollector_DownstreamError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DownstreamError'
type MockMetricsCollector_DownstreamError_Call struct {
	*mock.Call
}

// DownstreamError is a helper method to define mock.On call
//   - serverID string
//   - toolName string
//   - errType string
func (_e *MockMetricsCollector_Expecter) DownstreamError(serverID interface{}, toolName interface{}, errType interface{}) *MockMetricsCollector_DownstreamError_Call {
	return &MockMetricsCollector_DownstreamError_Call{Call: _e.mock.On("DownstreamError", serverID, toolName, errType)}
}

func (_c *MockMetricsCollector_DownstreamError_Call) Run(run func(serverID string, toolName string, errType string)) *MockMetricsCollector_DownstreamError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockMetricsCollector_DownstreamError_Call) Return() *MockMetricsCollector_DownstreamError_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockMetricsCollector_DownstreamError_Call) RunAndReturn(run func(string, string, string)) *MockMetricsCollector_DownstreamError_Call {
	_c.Run(run)
	return _c
}

// EnrollmentRequired provides a mock function with given fields: serverID
func (_m *MockMetricsCollector) EnrollmentRequired(serverID string) {
	_m.Called(serverID)
}

// MockMetricsCollector_EnrollmentRequired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnrollmentRequired'
type MockMetricsCollector_EnrollmentRequired_Call struct {
	*mock.Call
}

// EnrollmentRequired is a helper method to define mock.On call
//   - serverID string
func (_e *MockMetricsCollector_Expecter) EnrollmentRequired(serverID interface{}) *MockMetricsCollector_EnrollmentRequired_Call {
	return &MockMetricsCollector_EnrollmentRequired_Call{Call: _e.mock.On("EnrollmentRequired", serverID)}
}

func (_c *MockMetricsCollector_EnrollmentRequired_Call) Run(run func(serverID string)) *MockMetricsCollector_EnrollmentRequired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockMetricsCollector_EnrollmentRequired_Call) Return() *MockMetricsCollector_EnrollmentRequired_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockMetricsCollector_EnrollmentRequired_Call) RunAndReturn(run func(string)) *MockMetricsCollector_EnrollmentRequired_Call {
	_c.Run(run)
	return _c
}

// PolicyEvalError provides a mock function with given fields: serverID, toolName
func (_m *MockMetricsCollector) PolicyEvalError(serverID string, toolName string) {
	_m.Called(serverID, toolName)
}

// MockMetricsCollector_PolicyEvalError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PolicyEvalError'
type MockMetricsCollector_PolicyEvalError_Call struct {
	*mock.Call
}

// PolicyEvalError is a helper method to define mock.On call
//   - serverID string
//   - toolName string
func (_e *MockMetricsCollector_Expecter) PolicyEvalError(serverID interface{}, toolName interface{}) *MockMetricsCollector_PolicyEvalError_Call {
	return &MockMetricsCollector_PolicyEvalError_Call{Call: _e.mock.On("PolicyEvalError", serverID, toolName)}
}

func (_c *MockMetricsCollector_PolicyEvalError_Call) Run(run func(serverID string, toolName string)) *MockMetricsCollector_PolicyEvalError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockMetricsCollector_PolicyEvalError_Call) Return() *MockMetricsCollector_PolicyEvalError_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockMetricsCollector_PolicyEvalError_Call) RunAndReturn(run func(string, string)) *MockMetricsCollector_PolicyEvalError_Call {
	_c.Run(run)
	return _c
}

// ToolCallDuration provides a mock function with given fields: serverID, toolName, ms
func (_m *MockMetricsCollector) ToolCallDuration(serverID string, toolName string, ms int64) {
	_m.Called(serverID, toolName, ms)
}

// MockMetricsCollector_ToolCallDuration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToolCallDuration'
type MockMetricsCollector_ToolCallDuration_Call struct {
	*mock.Call
}

// ToolCallDuration is a helper method to define mock.On call
//   - serverID string
//   - toolName string
//   - ms int64
func (_e *MockMetricsCollector_Expecter) ToolCallDuration(serverID interface{}, toolName interface{}, ms interface{}) *MockMetricsCollector_ToolCallDuration_Call {
	return &MockMetricsCollector_ToolCallDuration_Call{Call: _e.mock.On("ToolCallDuration", serverID, toolName, ms)}
}

func (_c *MockMetricsCollector_ToolCallDuration_Call) Run(run func(serverID string, toolName string, ms int64)) *MockMetricsCollector_ToolCallDuration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(int64))
	})
	return _c
}

func (_c *MockMetricsCollector_ToolCallDuration_Call) Return() *MockMetricsCollector_ToolCallDuration_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockMetricsCollector_ToolCallDuration_Call) RunAndReturn(run func(string, string, int64)) *MockMetricsCollector_ToolCallDuration_Call {
	_c.Run(run)
	return _c
}

// ToolCallTotal provides a mock function with given fields: serverID, toolName, decision
func (_m *MockMetricsCollector) ToolCallTotal(serverID string, toolName string, decision string) {
	_m.Called(serverID, toolName, decision)
}

// MockMetricsCollector_ToolCallTotal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToolCallTotal'
type MockMetricsCollector_ToolCallTotal_Call struct {
	*mock.Call
}

// ToolCallTotal is a helper method to define mock.On call
//   - serverID string
//   - toolName string
//   - decision string
func (_e *MockMetricsCollector_Expecter) ToolCallTotal(serverID interface{}, toolName interface{}, decision interface{}) *MockMetricsCollector_ToolCallTotal_Call {
	return &MockMetricsCollector_ToolCallTotal_Call{Call: _e.mock.On("ToolCallTotal", serverID, toolName, decision)}
}

func (_c *MockMetricsCollector_ToolCallTotal_Call) Run(run func(serverID string, toolName string, decision string)) *MockMetricsCollector_ToolCallTotal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockMetricsCollector_ToolCallTotal_Call) Return() *MockMetricsCollector_ToolCallTotal_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockMetricsCollector_ToolCallTotal_Call) RunAndReturn(run func(string, string, string)) *MockMetricsCollector_ToolCallTotal_Call {
	_c.Run(run)
	return _c
}

// NewMockMetricsCollector creates a new instance of MockMetricsCollector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMetricsCollector(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMetricsCollector {
	mock := &MockMetricsCollector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
