// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	gateway "github.com/ro-eng/mcp-proxy/gateway"
	mock "github.com/stretchr/testify/mock"
)

// MockCredentialStore is an autogenerated mock type for the CredentialStore type
type MockCredentialStore struct {
	mock.Mock
}

type MockCredentialStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCredentialStore) EXPECT() *MockCredentialStore_Expecter {
	return &MockCredentialStore_Expecter{mock: &_m.Mock}
}

// List provides a mock function with given fields: ctx, identity
func (_m *MockCredentialStore) List(ctx context.Context, identity *gateway.Identity) ([]gateway.CredentialScope, error) {
	ret := _m.Called(ctx, identity)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []gateway.CredentialScope
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gateway.Identity) ([]gateway.CredentialScope, error)); ok {
		return rf(ctx, identity)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gateway.Identity) []gateway.CredentialScope); ok {
		r0 = rf(ctx, identity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]gateway.CredentialScope)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gateway.Identity) error); ok {
		r1 = rf(ctx, identity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCredentialStore_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockCredentialStore_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - identity *gateway.Identity
func (_e *MockCredentialStore_Expecter) List(ctx interface{}, identity interface{}) *MockCredentialStore_List_Call {
	return &MockCredentialStore_List_Call{Call: _e.mock.On("List", ctx, identity)}
}

func (_c *MockCredentialStore_List_Call) Run(run func(ctx context.Context, identity *gateway.Identity)) *MockCredentialStore_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*gateway.Identity))
	})
	return _c
}

func (_c *MockCredentialStore_List_Call) Return(_a0 []gateway.CredentialScope, _a1 error) *MockCredentialStore_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCredentialStore_List_Call) RunAndReturn(run func(context.Context, *gateway.Identity) ([]gateway.CredentialScope, error)) *MockCredentialStore_List_Call {
	_c.Call.Return(run)
	return _c
}

// Resolve provides a mock function with given fields: ctx, identity, serviceID
func (_m *MockCredentialStore) Resolve(ctx context.Context, identity *gateway.Identity, serviceID string) (*gateway.Credential, error) {
	ret := _m.Called(ctx, identity, serviceID)

	if len(ret) == 0 {
		panic("no return value specified for Resolve")
	}

	var r0 *gateway.Credential
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gateway.Identity, string) (*gateway.Credential, error)); ok {
		return rf(ctx, identity, serviceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gateway.Identity, string) *gateway.Credential); ok {
		r0 = rf(ctx, identity, serviceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gateway.Credential)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gateway.Identity, string) error); ok {
		r1 = rf(ctx, identity, serviceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCredentialStore_Resolve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resolve'
type MockCredentialStore_Resolve_Call struct {
	*mock.Call
}

// Resolve is a helper method to define mock.On call
//   - ctx context.Context
//   - identity *gateway.Identity
//   - serviceID string
func (_e *MockCredentialStore_Expecter) Resolve(ctx interface{}, identity interface{}, serviceID interface{}) *MockCredentialStore_Resolve_Call {
	return &MockCredentialStore_Resolve_Call{Call: _e.mock.On("Resolve", ctx, identity, serviceID)}
}

func (_c *MockCredentialStore_Resolve_Call) Run(run func(ctx context.Context, identity *gateway.Identity, serviceID string)) *MockCredentialStore_Resolve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*gateway.Identity), args[2].(string))
	})
	return _c
}

func (_c *MockCredentialStore_Resolve_Call) Return(_a0 *gateway.Credential, _a1 error) *MockCredentialStore_Resolve_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCredentialStore_Resolve_Call) RunAndReturn(run func(context.Context, *gateway.Identity, string) (*gateway.Credential, error)) *MockCredentialStore_Resolve_Call {
	_c.Call.Return(run)
	return _c
}

// Revoke provides a mock function with given fields: ctx, scope
func (_m *MockCredentialStore) Revoke(ctx context.Context, scope gateway.CredentialScope) error {
	ret := _m.Called(ctx, scope)

	if len(ret) == 0 {
		panic("no return value specified for Revoke")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, gateway.CredentialScope) error); ok {
		r0 = rf(ctx, scope)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCredentialStore_Revoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Revoke'
type MockCredentialStore_Revoke_Call struct {
	*mock.Call
}

// Revoke is a helper method to define mock.On call
//   - ctx context.Context
//   - scope gateway.CredentialScope
func (_e *MockCredentialStore_Expecter) Revoke(ctx interface{}, scope interface{}) *MockCredentialStore_Revoke_Call {
	return &MockCredentialStore_Revoke_Call{Call: _e.mock.On("Revoke", ctx, scope)}
}

func (_c *MockCredentialStore_Revoke_Call) Run(run func(ctx context.Context, scope gateway.CredentialScope)) *MockCredentialStore_Revoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(gateway.CredentialScope))
	})
	return _c
}

func (_c *MockCredentialStore_Revoke_Call) Return(_a0 error) *MockCredentialStore_Revoke_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCredentialStore_Revoke_Call) RunAndReturn(run func(context.Context, gateway.CredentialScope) error) *MockCredentialStore_Revoke_Call {
	_c.Call.Return(run)
	return _c
}

// Rotate provides a mock function with given fields: ctx, scope
func (_m *MockCredentialStore) Rotate(ctx context.Context, scope gateway.CredentialScope) (*gateway.Credential, error) {
	ret := _m.Called(ctx, scope)

	if len(ret) == 0 {
		panic("no return value specified for Rotate")
	}

	var r0 *gateway.Credential
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, gateway.CredentialScope) (*gateway.Credential, error)); ok {
		return rf(ctx, scope)
	}
	if rf, ok := ret.Get(0).(func(context.Context, gateway.CredentialScope) *gateway.Credential); ok {
		r0 = rf(ctx, scope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gateway.Credential)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, gateway.CredentialScope) error); ok {
		r1 = rf(ctx, scope)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCredentialStore_Rotate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rotate'
type MockCredentialStore_Rotate_Call struct {
	*mock.Call
}

// Rotate is a helper method to define mock.On call
//   - ctx context.Context
//   - scope gateway.CredentialScope
func (_e *MockCredentialStore_Expecter) Rotate(ctx interface{}, scope interface{}) *MockCredentialStore_Rotate_Call {
	return &MockCredentialStore_Rotate_Call{Call: _e.mock.On("Rotate", ctx, scope)}
}

func (_c *MockCredentialStore_Rotate_Call) Run(run func(ctx context.Context, scope gateway.CredentialScope)) *MockCredentialStore_Rotate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(gateway.CredentialScope))
	})
	return _c
}

func (_c *MockCredentialStore_Rotate_Call) Return(_a0 *gateway.Credential, _a1 error) *MockCredentialStore_Rotate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCredentialStore_Rotate_Call) RunAndReturn(run func(context.Context, gateway.CredentialScope) (*gateway.Credential, error)) *MockCredentialStore_Rotate_Call {
	_c.Call.Return(run)
	return _c
}

// Store provides a mock function with given fields: ctx, scope, cred
func (_m *MockCredentialStore) Store(ctx context.Context, scope gateway.CredentialScope, cred *gateway.Credential) error {
	ret := _m.Called(ctx, scope, cred)

	if len(ret) == 0 {
		panic("no return value specified for Store")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, gateway.CredentialScope, *gateway.Credential) error); ok {
		r0 = rf(ctx, scope, cred)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCredentialStore_Store_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Store'
type MockCredentialStore_Store_Call struct {
	*mock.Call
}

// Store is a helper method to define mock.On call
//   - ctx context.Context
//   - scope gateway.CredentialScope
//   - cred *gateway.Credential
func (_e *MockCredentialStore_Expecter) Store(ctx interface{}, scope interface{}, cred interface{}) *MockCredentialStore_Store_Call {
	return &MockCredentialStore_Store_Call{Call: _e.mock.On("Store", ctx, scope, cred)}
}

func (_c *MockCredentialStore_Store_Call) Run(run func(ctx context.Context, scope gateway.CredentialScope, cred *gateway.Credential)) *MockCredentialStore_Store_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(gateway.CredentialScope), args[2].(*gateway.Credential))
	})
	return _c
}

func (_c *MockCredentialStore_Store_Call) Return(_a0 error) *MockCredentialStore_Store_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCredentialStore_Store_Call) RunAndReturn(run func(context.Context, gateway.CredentialScope, *gateway.Credential) error) *MockCredentialStore_Store_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCredentialStore creates a new instance of MockCredentialStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCredentialStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCredentialStore {
	mock := &MockCredentialStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
